version: "3"

services:
    redis:
        container_name: redis
        image: redis:alpine

    db:
        container_name: db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: streamer
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: gotest

    rtmp:
        container_name: rtmp
        links:
            - web
        build:
            context: .
            dockerfile: ./scripts/rtmp/Dockerfile
        env_file:
            - ./scripts/prod.env
        entrypoint: ./wait-for-it.sh web:80 -- ./rtmp/init.sh
        restart: unless-stopped
        ports:
            - "1935:1935"
        expose:
            - 1935

    web:
        container_name: web
        links:
            - db
            - redis
        build:
            context: .
            dockerfile: ./scripts/web/Dockerfile
        entrypoint: ./wait-for-it.sh db:3306 -- ./web/init.sh
        restart: unless-stopped
        ports:
            - "4005:4005"
            - "80:80"
        expose:
            - 4005
            - 80
        env_file:
            - ./scripts/prod.env
